apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: vite-app
          image: us-central1-docker.pkg.dev/tasky-454515/tasky-frontend/frontend:latest
          ports:
            - containerPort: 80
